### ISSUE TITLE
Does not work with node 17

### ISSUE THREAD

**Issue by rdelorimiergloo** [markerikson/redux-quickstart-example-app#25]
If install and start is executed with node 16, the application works fine. However, with node 17 and error occurs. It would help if there were a requirements section in the readme to inform which node version this can be used with. Error:

Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/robertdelorimier/source/git_not_gloo/redux-essentials-example-app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/robertdelorimier/source/git_not_gloo/redux-essentials-example-app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/robertdelorimier/source/git_not_gloo/redux-essentials-example-app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/robertdelorimier/source/git_not_gloo/redux-essentials-example-app/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/robertdelorimier/source/git_not_gloo/redux-essentials-example-app/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/robertdelorimier/source/git_not_gloo/redux-essentials-example-app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/robertdelorimier/source/git_not_gloo/redux-essentials-example-app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/robertdelorimier/source/git_not_gloo/redux-essentials-example-app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/Users/robertdelorimier/source/git_not_gloo/redux-essentials-example-app/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/robertdelorimier/source/git_not_gloo/redux-essentials-example-app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/robertdelorimier/source/git_not_gloo/redux-essentials-example-app/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/robertdelorimier/source/git_not_gloo/redux-essentials-example-app/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/robertdelorimier/source/git_not_gloo/redux-essentials-example-app/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/robertdelorimier/source/git_not_gloo/redux-essentials-example-app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/robertdelorimier/source/git_not_gloo/redux-essentials-example-app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/robertdelorimier/source/git_not_gloo/redux-essentials-example-app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/robertdelorimier/source/git_not_gloo/redux-essentials-example-app/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by markerikson** [comment]
This is an issue with Node 17 itself in general, not a problem with the example repo specifically.  See:

https://github.com/webpack/webpack/issues/14532

**Comment by rdelorimiergloo** [comment]
That makes sense. I had thought that it would be an issue with how something in node is interacting with the examples. However, it still is a valid issue. 

Adding a bullet point/warning to the readme, alerting people new to react that the 17 version of node has an issue with the repo, would go a long way. This is the tutorial project, so it is pretty important that it actually works flawlessly. And I understand that you are very versant in react, and it seems obvious, but I am taking the tutorial because I am starting from ground zero, and it was not.

Please take this in the best light.

**Comment by markerikson** [comment]
Yeah, that's reasonable.  I need to do some edits to the tutorial code to fix another issue, and I'm hoping to do that in the next few days.  I can try to tweak the README while I'm at it.

**Comment by rdelorimiergloo** [comment]
Thank you for your help! Hopefully subsequent people will not stumble on this.
