### ISSUE TITLE
error:03000086:digital envelope routines::initialization error

### ISSUE THREAD

**Issue by dmitrybv** [markerikson/redux-quickstart-example-app#52]
When I downloaded the project as an archive and tried to run it in VSCode, I got the following errors.

```
> yarn start
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (C:\DelphiStuff\_WebTech\TestJS\40.redux-essentials-example\redux-essentials-example\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\DelphiStuff\_WebTech\TestJS\40.redux-essentials-example\redux-essentials-example\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\DelphiStuff\_WebTech\TestJS\40.redux-essentials-example\redux-essentials-example\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\DelphiStuff\_WebTech\TestJS\40.redux-essentials-example\redux-essentials-example\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\DelphiStuff\_WebTech\TestJS\40.redux-essentials-example\redux-essentials-example\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\DelphiStuff\_WebTech\TestJS\40.redux-essentials-example\redux-essentials-example\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\DelphiStuff\_WebTech\TestJS\40.redux-essentials-example\redux-essentials-example\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\DelphiStuff\_WebTech\TestJS\40.redux-essentials-example\redux-essentials-example\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
C:\DelphiStuff\_WebTech\TestJS\40.redux-essentials-example\redux-essentials-example\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (C:\DelphiStuff\_WebTech\TestJS\40.redux-essentials-example\redux-essentials-example\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\DelphiStuff\_WebTech\TestJS\40.redux-essentials-example\redux-essentials-example\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\DelphiStuff\_WebTech\TestJS\40.redux-essentials-example\redux-essentials-example\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\DelphiStuff\_WebTech\TestJS\40.redux-essentials-example\redux-essentials-example\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\DelphiStuff\_WebTech\TestJS\40.redux-essentials-example\redux-essentials-example\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\DelphiStuff\_WebTech\TestJS\40.redux-essentials-example\redux-essentials-example\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\DelphiStuff\_WebTech\TestJS\40.redux-essentials-example\redux-essentials-example\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\DelphiStuff\_WebTech\TestJS\40.redux-essentials-example\redux-essentials-example\node_modules\react-scripts\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v19.1.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by markerikson** [comment]
This is an issue with Node 18 and SSL settings:

https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

**Comment by dmitrybv** [comment]
In package.json changed "scripts" "start" to
    "start": "react-scripts --openssl-legacy-provider start",

Now Ok.
Thanks.
