### ISSUE TITLE
Error when I used npm start

### ISSUE THREAD

**Issue by acaemr22** [markerikson/redux-quickstart-example-app#58]
### When I installed the packages via npm i then I run the npm start and I got the following error:
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/workspaces/redux-essentials-example-app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/workspaces/redux-essentials-example-app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/workspaces/redux-essentials-example-app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /workspaces/redux-essentials-example-app/node_modules/webpack/lib/NormalModule.js:503:5
    at /workspaces/redux-essentials-example-app/node_modules/webpack/lib/NormalModule.js:358:12
    at /workspaces/redux-essentials-example-app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/workspaces/redux-essentials-example-app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/workspaces/redux-essentials-example-app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/workspaces/redux-essentials-example-app/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/workspaces/redux-essentials-example-app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/workspaces/redux-essentials-example-app/node_modules/webpack/lib/NormalModule.js:417:16)
    at /workspaces/redux-essentials-example-app/node_modules/webpack/lib/NormalModule.js:452:10
    at /workspaces/redux-essentials-example-app/node_modules/webpack/lib/NormalModule.js:323:13
    at /workspaces/redux-essentials-example-app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /workspaces/redux-essentials-example-app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/workspaces/redux-essentials-example-app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /workspaces/redux-essentials-example-app/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v19.9.0

### Can Node.js version be the reason why the command fails because Node v19 came to end of its life at 2023-06-01 ?

**Comment by acaemr22** [comment]
Same issue with https://github.com/reduxjs/redux-essentials-example-app/issues/52
