### ISSUE TITLE
Failed when adding Link in Navbar

### ISSUE THREAD

**Issue by yehtetmaungmaung** [markerikson/redux-quickstart-example-app#67]
I was following along redux essentials part 4 from documentation. When I add <Link> in Navbar to go to all posts components, the page doesn't show and throw below errors.

```
index.tsx:532 Uncaught TypeError: Cannot destructure property 'basename' of 'react__WEBPACK_IMPORTED_MODULE_0__.useContext(...)' as it is null.
    at LinkWithRef (index.tsx:532:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at updateForwardRef (react-dom.development.js:17044:1)
    at beginWork (react-dom.development.js:19098:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at scheduleUpdateOnFiber (react-dom.development.js:21881:1)
    at updateContainer (react-dom.development.js:25482:1)
    at react-dom.development.js:26021:1
    at unbatchedUpdates (react-dom.development.js:22431:1)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:26020:1)
    at Object.render (react-dom.development.js:26103:1)
    at start (index.js:15:1)
LinkWithRef @ index.tsx:532
renderWithHooks @ react-dom.development.js:14985
updateForwardRef @ react-dom.development.js:17044
beginWork @ react-dom.development.js:19098
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
scheduleUpdateOnFiber @ react-dom.development.js:21881
updateContainer @ react-dom.development.js:25482
(anonymous) @ react-dom.development.js:26021
unbatchedUpdates @ react-dom.development.js:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
start @ index.js:15
await in start (async)
(anonymous) @ index.js:25
./src/index.js @ index.js:26
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
1 @ index.js:26
__webpack_require__ @ bootstrap:851
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
index.js:1 The above error occurred in the <Link> component:

    at LinkWithRef (http://localhost:3000/static/js/vendors~main.chunk.js:129488:7)
    at div
    at div
    at section
    at nav
    at Navbar
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:132132:30)
    at BrowserRouter (http://localhost:3000/static/js/vendors~main.chunk.js:130216:35)
    at App
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:126718:20)
```

**Comment by markerikson** [comment]
Unfortunately this looks like some kind of error with React itself.

FWIW, I've recently migrated the example app to use Vite and the latest version of React, and hopefully that problem is gone at this point!
